#version: "3"

services:
  labjack:
    user: "${UID}:${GID}" 
    image: bradmears/labjack:latest
    hostname: labjack
    build: .
    privileged: true
    environment:
      - USER=${USER}
    volumes:
      - ${HOME}:${HOME}
      - /run/udev:/run/udev:ro
      - /dev/bus:/dev/bus
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    network_mode: host

